
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const ExpectedResponseLength = {
  short: 'short',
  medium: 'medium',
  long: 'long'
} as const

export type ExpectedResponseLength = (typeof ExpectedResponseLength)[keyof typeof ExpectedResponseLength]
