
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const QuestionType = {
  multiple_choice: 'multiple_choice',
  open_question: 'open_question',
  code_snippet: 'code_snippet'
} as const

export type QuestionType = (typeof QuestionType)[keyof typeof QuestionType]


export const ExpectedResponseLength = {
  short: 'short',
  medium: 'medium',
  long: 'long'
} as const

export type ExpectedResponseLength = (typeof ExpectedResponseLength)[keyof typeof ExpectedResponseLength]
