/**
 * Question Prompt Helpers
 *
 * Utility functions to help create type-specific question generation parameters
 * for the new modular prompt builder system.
 * Note: questionIndex was removed since question IDs are now generated by Prisma.
 */

import { QuestionType } from "../schemas";
import {
  BaseQuestionParams,
  CodeSnippetQuestionParams,
  GenerateQuestionParams,
  MultipleChoiceQuestionParams,
  OpenQuestionParams,
} from "../services/ai-service";
import { BehavioralScenarioQuestionParams } from "../services/ai/types";

// ====================
// PARAMETER BUILDERS
// ====================

/**
 * Creates base question parameters shared across all question types
 */
export const createBaseParams = (
  config: BaseQuestionParams,
): BaseQuestionParams => ({
  quizTitle: config.quizTitle,
  positionTitle: config.positionTitle,
  experienceLevel: config.experienceLevel,
  skills: config.skills,
  difficulty: config.difficulty || 3,
  previousQuestions: config.previousQuestions || [],
  specificModel: config.specificModel,
  instructions: config.instructions,
});

/**
 * Creates parameters for multiple choice question generation
 */
export const createMultipleChoiceParams = (
  baseConfig: BaseQuestionParams,
  options: {
    focusAreas?: string[];
    distractorComplexity?: "simple" | "moderate" | "complex";
  } = {},
): MultipleChoiceQuestionParams => ({
  ...createBaseParams(baseConfig),
  type: "multiple_choice",
  focusAreas: options.focusAreas,
  distractorComplexity: options.distractorComplexity,
});

/**
 * Creates parameters for open question generation
 */
export const createOpenQuestionParams = (
  baseConfig: BaseQuestionParams,
  options: {
    expectedResponseLength?: "short" | "medium" | "long";
    evaluationCriteria?: string[];
  } = {},
): OpenQuestionParams => ({
  ...createBaseParams(baseConfig),
  type: "open_question",
  expectedResponseLength: options.expectedResponseLength,
  evaluationCriteria: options.evaluationCriteria,
});

/**
 * Creates parameters for code snippet question generation
 */
export const createCodeSnippetParams = (
  baseConfig: BaseQuestionParams,
  options: {
    language?: string;
    bugType?: "syntax" | "logic" | "performance" | "security";
    codeComplexity?: "basic" | "intermediate" | "advanced";
    includeComments?: boolean;
  } = {},
): CodeSnippetQuestionParams => ({
  ...createBaseParams(baseConfig),
  type: "code_snippet",
  language: options.language,
  bugType: options.bugType,
  codeComplexity: options.codeComplexity,
  includeComments: options.includeComments,
});

/**
 * Creates parameters for behavioral scenario question generation
 */
export const createBehavioralScenarioParams = (
  baseConfig: BaseQuestionParams,
  options: {
    expectedResponseLength?: "short" | "medium" | "long";
    evaluationCriteria?: string[];
  } = {},
): BehavioralScenarioQuestionParams => ({
  ...createBaseParams(baseConfig),
  type: "behavioral_scenario",
  expectedResponseLength: options.expectedResponseLength,
  evaluationCriteria: options.evaluationCriteria,
});

// ====================
// CONVENIENCE FUNCTIONS
// ====================

/**
 * Creates question parameters based on type with sensible defaults
 */
export const createQuestionParams = (
  type: QuestionType,
  baseConfig: BaseQuestionParams,
  typeSpecificOptions?: Record<string, unknown>,
): GenerateQuestionParams => {
  switch (type) {
    case "multiple_choice":
      return createMultipleChoiceParams(baseConfig, typeSpecificOptions);
    case "open_question":
      return createOpenQuestionParams(baseConfig, typeSpecificOptions);
    case "code_snippet":
      return createCodeSnippetParams(baseConfig, typeSpecificOptions);
    case "behavioral_scenario":
      return createBehavioralScenarioParams(baseConfig, typeSpecificOptions);
    default:
      throw new Error(`Unsupported question type: ${type}`);
  }
};

/**
 * Creates parameters for frontend development questions with smart defaults
 */
export const createFrontendQuestionParams = (
  type: QuestionType,
  baseConfig: BaseQuestionParams,
): GenerateQuestionParams => {
  const frontendDefaults = {
    multiple_choice: {
      focusAreas: ["React", "JavaScript", "CSS", "DOM"],
      distractorComplexity: "moderate" as const,
    },
    open_question: {
      expectedResponseLength: "medium" as const,
      evaluationCriteria: [
        "technical accuracy",
        "best practices",
        "conceptual understanding",
      ],
    },
    code_snippet: {
      language: "javascript",
      bugType: "logic" as const,
      codeComplexity: "intermediate" as const,
      includeComments: true,
    },
    behavioral_scenario: {
      expectedResponseLength: "medium" as const,
      evaluationCriteria: ["collaboration", "decision-making", "communication"],
    },
  };

  return createQuestionParams(type, baseConfig, frontendDefaults[type]);
};

/**
 * Creates parameters for backend development questions with smart defaults
 */
export const createBackendQuestionParams = (
  type: QuestionType,
  baseConfig: BaseQuestionParams,
): GenerateQuestionParams => {
  const backendDefaults = {
    multiple_choice: {
      focusAreas: ["APIs", "databases", "server architecture", "security"],
      distractorComplexity: "complex" as const,
    },
    open_question: {
      expectedResponseLength: "long" as const,
      evaluationCriteria: [
        "system design",
        "scalability",
        "security considerations",
      ],
    },
    code_snippet: {
      language: "javascript", // Can be overridden
      bugType: "security" as const,
      codeComplexity: "advanced" as const,
      includeComments: true,
    },
    behavioral_scenario: {
      expectedResponseLength: "medium" as const,
      evaluationCriteria: [
        "decision-making",
        "communication",
        "risk awareness",
      ],
    },
  };

  return createQuestionParams(type, baseConfig, backendDefaults[type]);
};
