
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `QuizQuestion` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model QuizQuestion
 * 
 */
export type QuizQuestionModel = runtime.Types.Result.DefaultSelection<Prisma.$QuizQuestionPayload>

export type AggregateQuizQuestion = {
  _count: QuizQuestionCountAggregateOutputType | null
  _avg: QuizQuestionAvgAggregateOutputType | null
  _sum: QuizQuestionSumAggregateOutputType | null
  _min: QuizQuestionMinAggregateOutputType | null
  _max: QuizQuestionMaxAggregateOutputType | null
}

export type QuizQuestionAvgAggregateOutputType = {
  order: number | null
}

export type QuizQuestionSumAggregateOutputType = {
  order: number | null
}

export type QuizQuestionMinAggregateOutputType = {
  id: string | null
  quizId: string | null
  questionId: string | null
  order: number | null
  createdAt: Date | null
}

export type QuizQuestionMaxAggregateOutputType = {
  id: string | null
  quizId: string | null
  questionId: string | null
  order: number | null
  createdAt: Date | null
}

export type QuizQuestionCountAggregateOutputType = {
  id: number
  quizId: number
  questionId: number
  order: number
  createdAt: number
  _all: number
}


export type QuizQuestionAvgAggregateInputType = {
  order?: true
}

export type QuizQuestionSumAggregateInputType = {
  order?: true
}

export type QuizQuestionMinAggregateInputType = {
  id?: true
  quizId?: true
  questionId?: true
  order?: true
  createdAt?: true
}

export type QuizQuestionMaxAggregateInputType = {
  id?: true
  quizId?: true
  questionId?: true
  order?: true
  createdAt?: true
}

export type QuizQuestionCountAggregateInputType = {
  id?: true
  quizId?: true
  questionId?: true
  order?: true
  createdAt?: true
  _all?: true
}

export type QuizQuestionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which QuizQuestion to aggregate.
   */
  where?: Prisma.QuizQuestionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuizQuestions to fetch.
   */
  orderBy?: Prisma.QuizQuestionOrderByWithRelationInput | Prisma.QuizQuestionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.QuizQuestionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuizQuestions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuizQuestions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned QuizQuestions
  **/
  _count?: true | QuizQuestionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: QuizQuestionAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: QuizQuestionSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: QuizQuestionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: QuizQuestionMaxAggregateInputType
}

export type GetQuizQuestionAggregateType<T extends QuizQuestionAggregateArgs> = {
      [P in keyof T & keyof AggregateQuizQuestion]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateQuizQuestion[P]>
    : Prisma.GetScalarType<T[P], AggregateQuizQuestion[P]>
}




export type QuizQuestionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.QuizQuestionWhereInput
  orderBy?: Prisma.QuizQuestionOrderByWithAggregationInput | Prisma.QuizQuestionOrderByWithAggregationInput[]
  by: Prisma.QuizQuestionScalarFieldEnum[] | Prisma.QuizQuestionScalarFieldEnum
  having?: Prisma.QuizQuestionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: QuizQuestionCountAggregateInputType | true
  _avg?: QuizQuestionAvgAggregateInputType
  _sum?: QuizQuestionSumAggregateInputType
  _min?: QuizQuestionMinAggregateInputType
  _max?: QuizQuestionMaxAggregateInputType
}

export type QuizQuestionGroupByOutputType = {
  id: string
  quizId: string
  questionId: string
  order: number
  createdAt: Date
  _count: QuizQuestionCountAggregateOutputType | null
  _avg: QuizQuestionAvgAggregateOutputType | null
  _sum: QuizQuestionSumAggregateOutputType | null
  _min: QuizQuestionMinAggregateOutputType | null
  _max: QuizQuestionMaxAggregateOutputType | null
}

type GetQuizQuestionGroupByPayload<T extends QuizQuestionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<QuizQuestionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof QuizQuestionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], QuizQuestionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], QuizQuestionGroupByOutputType[P]>
      }
    >
  >



export type QuizQuestionWhereInput = {
  AND?: Prisma.QuizQuestionWhereInput | Prisma.QuizQuestionWhereInput[]
  OR?: Prisma.QuizQuestionWhereInput[]
  NOT?: Prisma.QuizQuestionWhereInput | Prisma.QuizQuestionWhereInput[]
  id?: Prisma.StringFilter<"QuizQuestion"> | string
  quizId?: Prisma.StringFilter<"QuizQuestion"> | string
  questionId?: Prisma.StringFilter<"QuizQuestion"> | string
  order?: Prisma.IntFilter<"QuizQuestion"> | number
  createdAt?: Prisma.DateTimeFilter<"QuizQuestion"> | Date | string
  quiz?: Prisma.XOR<Prisma.QuizScalarRelationFilter, Prisma.QuizWhereInput>
  question?: Prisma.XOR<Prisma.QuestionScalarRelationFilter, Prisma.QuestionWhereInput>
}

export type QuizQuestionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  quizId?: Prisma.SortOrder
  questionId?: Prisma.SortOrder
  order?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  quiz?: Prisma.QuizOrderByWithRelationInput
  question?: Prisma.QuestionOrderByWithRelationInput
}

export type QuizQuestionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  quizId_questionId?: Prisma.QuizQuestionQuizIdQuestionIdCompoundUniqueInput
  AND?: Prisma.QuizQuestionWhereInput | Prisma.QuizQuestionWhereInput[]
  OR?: Prisma.QuizQuestionWhereInput[]
  NOT?: Prisma.QuizQuestionWhereInput | Prisma.QuizQuestionWhereInput[]
  quizId?: Prisma.StringFilter<"QuizQuestion"> | string
  questionId?: Prisma.StringFilter<"QuizQuestion"> | string
  order?: Prisma.IntFilter<"QuizQuestion"> | number
  createdAt?: Prisma.DateTimeFilter<"QuizQuestion"> | Date | string
  quiz?: Prisma.XOR<Prisma.QuizScalarRelationFilter, Prisma.QuizWhereInput>
  question?: Prisma.XOR<Prisma.QuestionScalarRelationFilter, Prisma.QuestionWhereInput>
}, "id" | "quizId_questionId">

export type QuizQuestionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  quizId?: Prisma.SortOrder
  questionId?: Prisma.SortOrder
  order?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.QuizQuestionCountOrderByAggregateInput
  _avg?: Prisma.QuizQuestionAvgOrderByAggregateInput
  _max?: Prisma.QuizQuestionMaxOrderByAggregateInput
  _min?: Prisma.QuizQuestionMinOrderByAggregateInput
  _sum?: Prisma.QuizQuestionSumOrderByAggregateInput
}

export type QuizQuestionScalarWhereWithAggregatesInput = {
  AND?: Prisma.QuizQuestionScalarWhereWithAggregatesInput | Prisma.QuizQuestionScalarWhereWithAggregatesInput[]
  OR?: Prisma.QuizQuestionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.QuizQuestionScalarWhereWithAggregatesInput | Prisma.QuizQuestionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"QuizQuestion"> | string
  quizId?: Prisma.StringWithAggregatesFilter<"QuizQuestion"> | string
  questionId?: Prisma.StringWithAggregatesFilter<"QuizQuestion"> | string
  order?: Prisma.IntWithAggregatesFilter<"QuizQuestion"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"QuizQuestion"> | Date | string
}

export type QuizQuestionCreateInput = {
  id?: string
  order: number
  createdAt?: Date | string
  quiz: Prisma.QuizCreateNestedOneWithoutQuizQuestionsInput
  question: Prisma.QuestionCreateNestedOneWithoutQuizQuestionsInput
}

export type QuizQuestionUncheckedCreateInput = {
  id?: string
  quizId: string
  questionId: string
  order: number
  createdAt?: Date | string
}

export type QuizQuestionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  quiz?: Prisma.QuizUpdateOneRequiredWithoutQuizQuestionsNestedInput
  question?: Prisma.QuestionUpdateOneRequiredWithoutQuizQuestionsNestedInput
}

export type QuizQuestionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  quizId?: Prisma.StringFieldUpdateOperationsInput | string
  questionId?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type QuizQuestionCreateManyInput = {
  id?: string
  quizId: string
  questionId: string
  order: number
  createdAt?: Date | string
}

export type QuizQuestionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type QuizQuestionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  quizId?: Prisma.StringFieldUpdateOperationsInput | string
  questionId?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type QuizQuestionListRelationFilter = {
  every?: Prisma.QuizQuestionWhereInput
  some?: Prisma.QuizQuestionWhereInput
  none?: Prisma.QuizQuestionWhereInput
}

export type QuizQuestionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type QuizQuestionQuizIdQuestionIdCompoundUniqueInput = {
  quizId: string
  questionId: string
}

export type QuizQuestionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  quizId?: Prisma.SortOrder
  questionId?: Prisma.SortOrder
  order?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type QuizQuestionAvgOrderByAggregateInput = {
  order?: Prisma.SortOrder
}

export type QuizQuestionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  quizId?: Prisma.SortOrder
  questionId?: Prisma.SortOrder
  order?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type QuizQuestionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  quizId?: Prisma.SortOrder
  questionId?: Prisma.SortOrder
  order?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type QuizQuestionSumOrderByAggregateInput = {
  order?: Prisma.SortOrder
}

export type QuizQuestionCreateNestedManyWithoutQuizInput = {
  create?: Prisma.XOR<Prisma.QuizQuestionCreateWithoutQuizInput, Prisma.QuizQuestionUncheckedCreateWithoutQuizInput> | Prisma.QuizQuestionCreateWithoutQuizInput[] | Prisma.QuizQuestionUncheckedCreateWithoutQuizInput[]
  connectOrCreate?: Prisma.QuizQuestionCreateOrConnectWithoutQuizInput | Prisma.QuizQuestionCreateOrConnectWithoutQuizInput[]
  createMany?: Prisma.QuizQuestionCreateManyQuizInputEnvelope
  connect?: Prisma.QuizQuestionWhereUniqueInput | Prisma.QuizQuestionWhereUniqueInput[]
}

export type QuizQuestionUncheckedCreateNestedManyWithoutQuizInput = {
  create?: Prisma.XOR<Prisma.QuizQuestionCreateWithoutQuizInput, Prisma.QuizQuestionUncheckedCreateWithoutQuizInput> | Prisma.QuizQuestionCreateWithoutQuizInput[] | Prisma.QuizQuestionUncheckedCreateWithoutQuizInput[]
  connectOrCreate?: Prisma.QuizQuestionCreateOrConnectWithoutQuizInput | Prisma.QuizQuestionCreateOrConnectWithoutQuizInput[]
  createMany?: Prisma.QuizQuestionCreateManyQuizInputEnvelope
  connect?: Prisma.QuizQuestionWhereUniqueInput | Prisma.QuizQuestionWhereUniqueInput[]
}

export type QuizQuestionUpdateManyWithoutQuizNestedInput = {
  create?: Prisma.XOR<Prisma.QuizQuestionCreateWithoutQuizInput, Prisma.QuizQuestionUncheckedCreateWithoutQuizInput> | Prisma.QuizQuestionCreateWithoutQuizInput[] | Prisma.QuizQuestionUncheckedCreateWithoutQuizInput[]
  connectOrCreate?: Prisma.QuizQuestionCreateOrConnectWithoutQuizInput | Prisma.QuizQuestionCreateOrConnectWithoutQuizInput[]
  upsert?: Prisma.QuizQuestionUpsertWithWhereUniqueWithoutQuizInput | Prisma.QuizQuestionUpsertWithWhereUniqueWithoutQuizInput[]
  createMany?: Prisma.QuizQuestionCreateManyQuizInputEnvelope
  set?: Prisma.QuizQuestionWhereUniqueInput | Prisma.QuizQuestionWhereUniqueInput[]
  disconnect?: Prisma.QuizQuestionWhereUniqueInput | Prisma.QuizQuestionWhereUniqueInput[]
  delete?: Prisma.QuizQuestionWhereUniqueInput | Prisma.QuizQuestionWhereUniqueInput[]
  connect?: Prisma.QuizQuestionWhereUniqueInput | Prisma.QuizQuestionWhereUniqueInput[]
  update?: Prisma.QuizQuestionUpdateWithWhereUniqueWithoutQuizInput | Prisma.QuizQuestionUpdateWithWhereUniqueWithoutQuizInput[]
  updateMany?: Prisma.QuizQuestionUpdateManyWithWhereWithoutQuizInput | Prisma.QuizQuestionUpdateManyWithWhereWithoutQuizInput[]
  deleteMany?: Prisma.QuizQuestionScalarWhereInput | Prisma.QuizQuestionScalarWhereInput[]
}

export type QuizQuestionUncheckedUpdateManyWithoutQuizNestedInput = {
  create?: Prisma.XOR<Prisma.QuizQuestionCreateWithoutQuizInput, Prisma.QuizQuestionUncheckedCreateWithoutQuizInput> | Prisma.QuizQuestionCreateWithoutQuizInput[] | Prisma.QuizQuestionUncheckedCreateWithoutQuizInput[]
  connectOrCreate?: Prisma.QuizQuestionCreateOrConnectWithoutQuizInput | Prisma.QuizQuestionCreateOrConnectWithoutQuizInput[]
  upsert?: Prisma.QuizQuestionUpsertWithWhereUniqueWithoutQuizInput | Prisma.QuizQuestionUpsertWithWhereUniqueWithoutQuizInput[]
  createMany?: Prisma.QuizQuestionCreateManyQuizInputEnvelope
  set?: Prisma.QuizQuestionWhereUniqueInput | Prisma.QuizQuestionWhereUniqueInput[]
  disconnect?: Prisma.QuizQuestionWhereUniqueInput | Prisma.QuizQuestionWhereUniqueInput[]
  delete?: Prisma.QuizQuestionWhereUniqueInput | Prisma.QuizQuestionWhereUniqueInput[]
  connect?: Prisma.QuizQuestionWhereUniqueInput | Prisma.QuizQuestionWhereUniqueInput[]
  update?: Prisma.QuizQuestionUpdateWithWhereUniqueWithoutQuizInput | Prisma.QuizQuestionUpdateWithWhereUniqueWithoutQuizInput[]
  updateMany?: Prisma.QuizQuestionUpdateManyWithWhereWithoutQuizInput | Prisma.QuizQuestionUpdateManyWithWhereWithoutQuizInput[]
  deleteMany?: Prisma.QuizQuestionScalarWhereInput | Prisma.QuizQuestionScalarWhereInput[]
}

export type QuizQuestionCreateNestedManyWithoutQuestionInput = {
  create?: Prisma.XOR<Prisma.QuizQuestionCreateWithoutQuestionInput, Prisma.QuizQuestionUncheckedCreateWithoutQuestionInput> | Prisma.QuizQuestionCreateWithoutQuestionInput[] | Prisma.QuizQuestionUncheckedCreateWithoutQuestionInput[]
  connectOrCreate?: Prisma.QuizQuestionCreateOrConnectWithoutQuestionInput | Prisma.QuizQuestionCreateOrConnectWithoutQuestionInput[]
  createMany?: Prisma.QuizQuestionCreateManyQuestionInputEnvelope
  connect?: Prisma.QuizQuestionWhereUniqueInput | Prisma.QuizQuestionWhereUniqueInput[]
}

export type QuizQuestionUncheckedCreateNestedManyWithoutQuestionInput = {
  create?: Prisma.XOR<Prisma.QuizQuestionCreateWithoutQuestionInput, Prisma.QuizQuestionUncheckedCreateWithoutQuestionInput> | Prisma.QuizQuestionCreateWithoutQuestionInput[] | Prisma.QuizQuestionUncheckedCreateWithoutQuestionInput[]
  connectOrCreate?: Prisma.QuizQuestionCreateOrConnectWithoutQuestionInput | Prisma.QuizQuestionCreateOrConnectWithoutQuestionInput[]
  createMany?: Prisma.QuizQuestionCreateManyQuestionInputEnvelope
  connect?: Prisma.QuizQuestionWhereUniqueInput | Prisma.QuizQuestionWhereUniqueInput[]
}

export type QuizQuestionUpdateManyWithoutQuestionNestedInput = {
  create?: Prisma.XOR<Prisma.QuizQuestionCreateWithoutQuestionInput, Prisma.QuizQuestionUncheckedCreateWithoutQuestionInput> | Prisma.QuizQuestionCreateWithoutQuestionInput[] | Prisma.QuizQuestionUncheckedCreateWithoutQuestionInput[]
  connectOrCreate?: Prisma.QuizQuestionCreateOrConnectWithoutQuestionInput | Prisma.QuizQuestionCreateOrConnectWithoutQuestionInput[]
  upsert?: Prisma.QuizQuestionUpsertWithWhereUniqueWithoutQuestionInput | Prisma.QuizQuestionUpsertWithWhereUniqueWithoutQuestionInput[]
  createMany?: Prisma.QuizQuestionCreateManyQuestionInputEnvelope
  set?: Prisma.QuizQuestionWhereUniqueInput | Prisma.QuizQuestionWhereUniqueInput[]
  disconnect?: Prisma.QuizQuestionWhereUniqueInput | Prisma.QuizQuestionWhereUniqueInput[]
  delete?: Prisma.QuizQuestionWhereUniqueInput | Prisma.QuizQuestionWhereUniqueInput[]
  connect?: Prisma.QuizQuestionWhereUniqueInput | Prisma.QuizQuestionWhereUniqueInput[]
  update?: Prisma.QuizQuestionUpdateWithWhereUniqueWithoutQuestionInput | Prisma.QuizQuestionUpdateWithWhereUniqueWithoutQuestionInput[]
  updateMany?: Prisma.QuizQuestionUpdateManyWithWhereWithoutQuestionInput | Prisma.QuizQuestionUpdateManyWithWhereWithoutQuestionInput[]
  deleteMany?: Prisma.QuizQuestionScalarWhereInput | Prisma.QuizQuestionScalarWhereInput[]
}

export type QuizQuestionUncheckedUpdateManyWithoutQuestionNestedInput = {
  create?: Prisma.XOR<Prisma.QuizQuestionCreateWithoutQuestionInput, Prisma.QuizQuestionUncheckedCreateWithoutQuestionInput> | Prisma.QuizQuestionCreateWithoutQuestionInput[] | Prisma.QuizQuestionUncheckedCreateWithoutQuestionInput[]
  connectOrCreate?: Prisma.QuizQuestionCreateOrConnectWithoutQuestionInput | Prisma.QuizQuestionCreateOrConnectWithoutQuestionInput[]
  upsert?: Prisma.QuizQuestionUpsertWithWhereUniqueWithoutQuestionInput | Prisma.QuizQuestionUpsertWithWhereUniqueWithoutQuestionInput[]
  createMany?: Prisma.QuizQuestionCreateManyQuestionInputEnvelope
  set?: Prisma.QuizQuestionWhereUniqueInput | Prisma.QuizQuestionWhereUniqueInput[]
  disconnect?: Prisma.QuizQuestionWhereUniqueInput | Prisma.QuizQuestionWhereUniqueInput[]
  delete?: Prisma.QuizQuestionWhereUniqueInput | Prisma.QuizQuestionWhereUniqueInput[]
  connect?: Prisma.QuizQuestionWhereUniqueInput | Prisma.QuizQuestionWhereUniqueInput[]
  update?: Prisma.QuizQuestionUpdateWithWhereUniqueWithoutQuestionInput | Prisma.QuizQuestionUpdateWithWhereUniqueWithoutQuestionInput[]
  updateMany?: Prisma.QuizQuestionUpdateManyWithWhereWithoutQuestionInput | Prisma.QuizQuestionUpdateManyWithWhereWithoutQuestionInput[]
  deleteMany?: Prisma.QuizQuestionScalarWhereInput | Prisma.QuizQuestionScalarWhereInput[]
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type QuizQuestionCreateWithoutQuizInput = {
  id?: string
  order: number
  createdAt?: Date | string
  question: Prisma.QuestionCreateNestedOneWithoutQuizQuestionsInput
}

export type QuizQuestionUncheckedCreateWithoutQuizInput = {
  id?: string
  questionId: string
  order: number
  createdAt?: Date | string
}

export type QuizQuestionCreateOrConnectWithoutQuizInput = {
  where: Prisma.QuizQuestionWhereUniqueInput
  create: Prisma.XOR<Prisma.QuizQuestionCreateWithoutQuizInput, Prisma.QuizQuestionUncheckedCreateWithoutQuizInput>
}

export type QuizQuestionCreateManyQuizInputEnvelope = {
  data: Prisma.QuizQuestionCreateManyQuizInput | Prisma.QuizQuestionCreateManyQuizInput[]
  skipDuplicates?: boolean
}

export type QuizQuestionUpsertWithWhereUniqueWithoutQuizInput = {
  where: Prisma.QuizQuestionWhereUniqueInput
  update: Prisma.XOR<Prisma.QuizQuestionUpdateWithoutQuizInput, Prisma.QuizQuestionUncheckedUpdateWithoutQuizInput>
  create: Prisma.XOR<Prisma.QuizQuestionCreateWithoutQuizInput, Prisma.QuizQuestionUncheckedCreateWithoutQuizInput>
}

export type QuizQuestionUpdateWithWhereUniqueWithoutQuizInput = {
  where: Prisma.QuizQuestionWhereUniqueInput
  data: Prisma.XOR<Prisma.QuizQuestionUpdateWithoutQuizInput, Prisma.QuizQuestionUncheckedUpdateWithoutQuizInput>
}

export type QuizQuestionUpdateManyWithWhereWithoutQuizInput = {
  where: Prisma.QuizQuestionScalarWhereInput
  data: Prisma.XOR<Prisma.QuizQuestionUpdateManyMutationInput, Prisma.QuizQuestionUncheckedUpdateManyWithoutQuizInput>
}

export type QuizQuestionScalarWhereInput = {
  AND?: Prisma.QuizQuestionScalarWhereInput | Prisma.QuizQuestionScalarWhereInput[]
  OR?: Prisma.QuizQuestionScalarWhereInput[]
  NOT?: Prisma.QuizQuestionScalarWhereInput | Prisma.QuizQuestionScalarWhereInput[]
  id?: Prisma.StringFilter<"QuizQuestion"> | string
  quizId?: Prisma.StringFilter<"QuizQuestion"> | string
  questionId?: Prisma.StringFilter<"QuizQuestion"> | string
  order?: Prisma.IntFilter<"QuizQuestion"> | number
  createdAt?: Prisma.DateTimeFilter<"QuizQuestion"> | Date | string
}

export type QuizQuestionCreateWithoutQuestionInput = {
  id?: string
  order: number
  createdAt?: Date | string
  quiz: Prisma.QuizCreateNestedOneWithoutQuizQuestionsInput
}

export type QuizQuestionUncheckedCreateWithoutQuestionInput = {
  id?: string
  quizId: string
  order: number
  createdAt?: Date | string
}

export type QuizQuestionCreateOrConnectWithoutQuestionInput = {
  where: Prisma.QuizQuestionWhereUniqueInput
  create: Prisma.XOR<Prisma.QuizQuestionCreateWithoutQuestionInput, Prisma.QuizQuestionUncheckedCreateWithoutQuestionInput>
}

export type QuizQuestionCreateManyQuestionInputEnvelope = {
  data: Prisma.QuizQuestionCreateManyQuestionInput | Prisma.QuizQuestionCreateManyQuestionInput[]
  skipDuplicates?: boolean
}

export type QuizQuestionUpsertWithWhereUniqueWithoutQuestionInput = {
  where: Prisma.QuizQuestionWhereUniqueInput
  update: Prisma.XOR<Prisma.QuizQuestionUpdateWithoutQuestionInput, Prisma.QuizQuestionUncheckedUpdateWithoutQuestionInput>
  create: Prisma.XOR<Prisma.QuizQuestionCreateWithoutQuestionInput, Prisma.QuizQuestionUncheckedCreateWithoutQuestionInput>
}

export type QuizQuestionUpdateWithWhereUniqueWithoutQuestionInput = {
  where: Prisma.QuizQuestionWhereUniqueInput
  data: Prisma.XOR<Prisma.QuizQuestionUpdateWithoutQuestionInput, Prisma.QuizQuestionUncheckedUpdateWithoutQuestionInput>
}

export type QuizQuestionUpdateManyWithWhereWithoutQuestionInput = {
  where: Prisma.QuizQuestionScalarWhereInput
  data: Prisma.XOR<Prisma.QuizQuestionUpdateManyMutationInput, Prisma.QuizQuestionUncheckedUpdateManyWithoutQuestionInput>
}

export type QuizQuestionCreateManyQuizInput = {
  id?: string
  questionId: string
  order: number
  createdAt?: Date | string
}

export type QuizQuestionUpdateWithoutQuizInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  question?: Prisma.QuestionUpdateOneRequiredWithoutQuizQuestionsNestedInput
}

export type QuizQuestionUncheckedUpdateWithoutQuizInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  questionId?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type QuizQuestionUncheckedUpdateManyWithoutQuizInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  questionId?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type QuizQuestionCreateManyQuestionInput = {
  id?: string
  quizId: string
  order: number
  createdAt?: Date | string
}

export type QuizQuestionUpdateWithoutQuestionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  quiz?: Prisma.QuizUpdateOneRequiredWithoutQuizQuestionsNestedInput
}

export type QuizQuestionUncheckedUpdateWithoutQuestionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  quizId?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type QuizQuestionUncheckedUpdateManyWithoutQuestionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  quizId?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type QuizQuestionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  quizId?: boolean
  questionId?: boolean
  order?: boolean
  createdAt?: boolean
  quiz?: boolean | Prisma.QuizDefaultArgs<ExtArgs>
  question?: boolean | Prisma.QuestionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["quizQuestion"]>

export type QuizQuestionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  quizId?: boolean
  questionId?: boolean
  order?: boolean
  createdAt?: boolean
  quiz?: boolean | Prisma.QuizDefaultArgs<ExtArgs>
  question?: boolean | Prisma.QuestionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["quizQuestion"]>

export type QuizQuestionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  quizId?: boolean
  questionId?: boolean
  order?: boolean
  createdAt?: boolean
  quiz?: boolean | Prisma.QuizDefaultArgs<ExtArgs>
  question?: boolean | Prisma.QuestionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["quizQuestion"]>

export type QuizQuestionSelectScalar = {
  id?: boolean
  quizId?: boolean
  questionId?: boolean
  order?: boolean
  createdAt?: boolean
}

export type QuizQuestionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "quizId" | "questionId" | "order" | "createdAt", ExtArgs["result"]["quizQuestion"]>
export type QuizQuestionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  quiz?: boolean | Prisma.QuizDefaultArgs<ExtArgs>
  question?: boolean | Prisma.QuestionDefaultArgs<ExtArgs>
}
export type QuizQuestionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  quiz?: boolean | Prisma.QuizDefaultArgs<ExtArgs>
  question?: boolean | Prisma.QuestionDefaultArgs<ExtArgs>
}
export type QuizQuestionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  quiz?: boolean | Prisma.QuizDefaultArgs<ExtArgs>
  question?: boolean | Prisma.QuestionDefaultArgs<ExtArgs>
}

export type $QuizQuestionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "QuizQuestion"
  objects: {
    quiz: Prisma.$QuizPayload<ExtArgs>
    question: Prisma.$QuestionPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    quizId: string
    questionId: string
    order: number
    createdAt: Date
  }, ExtArgs["result"]["quizQuestion"]>
  composites: {}
}

export type QuizQuestionGetPayload<S extends boolean | null | undefined | QuizQuestionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$QuizQuestionPayload, S>

export type QuizQuestionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<QuizQuestionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: QuizQuestionCountAggregateInputType | true
  }

export interface QuizQuestionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['QuizQuestion'], meta: { name: 'QuizQuestion' } }
  /**
   * Find zero or one QuizQuestion that matches the filter.
   * @param {QuizQuestionFindUniqueArgs} args - Arguments to find a QuizQuestion
   * @example
   * // Get one QuizQuestion
   * const quizQuestion = await prisma.quizQuestion.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends QuizQuestionFindUniqueArgs>(args: Prisma.SelectSubset<T, QuizQuestionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__QuizQuestionClient<runtime.Types.Result.GetResult<Prisma.$QuizQuestionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one QuizQuestion that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {QuizQuestionFindUniqueOrThrowArgs} args - Arguments to find a QuizQuestion
   * @example
   * // Get one QuizQuestion
   * const quizQuestion = await prisma.quizQuestion.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends QuizQuestionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, QuizQuestionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__QuizQuestionClient<runtime.Types.Result.GetResult<Prisma.$QuizQuestionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first QuizQuestion that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuizQuestionFindFirstArgs} args - Arguments to find a QuizQuestion
   * @example
   * // Get one QuizQuestion
   * const quizQuestion = await prisma.quizQuestion.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends QuizQuestionFindFirstArgs>(args?: Prisma.SelectSubset<T, QuizQuestionFindFirstArgs<ExtArgs>>): Prisma.Prisma__QuizQuestionClient<runtime.Types.Result.GetResult<Prisma.$QuizQuestionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first QuizQuestion that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuizQuestionFindFirstOrThrowArgs} args - Arguments to find a QuizQuestion
   * @example
   * // Get one QuizQuestion
   * const quizQuestion = await prisma.quizQuestion.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends QuizQuestionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, QuizQuestionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__QuizQuestionClient<runtime.Types.Result.GetResult<Prisma.$QuizQuestionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more QuizQuestions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuizQuestionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all QuizQuestions
   * const quizQuestions = await prisma.quizQuestion.findMany()
   * 
   * // Get first 10 QuizQuestions
   * const quizQuestions = await prisma.quizQuestion.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const quizQuestionWithIdOnly = await prisma.quizQuestion.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends QuizQuestionFindManyArgs>(args?: Prisma.SelectSubset<T, QuizQuestionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuizQuestionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a QuizQuestion.
   * @param {QuizQuestionCreateArgs} args - Arguments to create a QuizQuestion.
   * @example
   * // Create one QuizQuestion
   * const QuizQuestion = await prisma.quizQuestion.create({
   *   data: {
   *     // ... data to create a QuizQuestion
   *   }
   * })
   * 
   */
  create<T extends QuizQuestionCreateArgs>(args: Prisma.SelectSubset<T, QuizQuestionCreateArgs<ExtArgs>>): Prisma.Prisma__QuizQuestionClient<runtime.Types.Result.GetResult<Prisma.$QuizQuestionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many QuizQuestions.
   * @param {QuizQuestionCreateManyArgs} args - Arguments to create many QuizQuestions.
   * @example
   * // Create many QuizQuestions
   * const quizQuestion = await prisma.quizQuestion.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends QuizQuestionCreateManyArgs>(args?: Prisma.SelectSubset<T, QuizQuestionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many QuizQuestions and returns the data saved in the database.
   * @param {QuizQuestionCreateManyAndReturnArgs} args - Arguments to create many QuizQuestions.
   * @example
   * // Create many QuizQuestions
   * const quizQuestion = await prisma.quizQuestion.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many QuizQuestions and only return the `id`
   * const quizQuestionWithIdOnly = await prisma.quizQuestion.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends QuizQuestionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, QuizQuestionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuizQuestionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a QuizQuestion.
   * @param {QuizQuestionDeleteArgs} args - Arguments to delete one QuizQuestion.
   * @example
   * // Delete one QuizQuestion
   * const QuizQuestion = await prisma.quizQuestion.delete({
   *   where: {
   *     // ... filter to delete one QuizQuestion
   *   }
   * })
   * 
   */
  delete<T extends QuizQuestionDeleteArgs>(args: Prisma.SelectSubset<T, QuizQuestionDeleteArgs<ExtArgs>>): Prisma.Prisma__QuizQuestionClient<runtime.Types.Result.GetResult<Prisma.$QuizQuestionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one QuizQuestion.
   * @param {QuizQuestionUpdateArgs} args - Arguments to update one QuizQuestion.
   * @example
   * // Update one QuizQuestion
   * const quizQuestion = await prisma.quizQuestion.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends QuizQuestionUpdateArgs>(args: Prisma.SelectSubset<T, QuizQuestionUpdateArgs<ExtArgs>>): Prisma.Prisma__QuizQuestionClient<runtime.Types.Result.GetResult<Prisma.$QuizQuestionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more QuizQuestions.
   * @param {QuizQuestionDeleteManyArgs} args - Arguments to filter QuizQuestions to delete.
   * @example
   * // Delete a few QuizQuestions
   * const { count } = await prisma.quizQuestion.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends QuizQuestionDeleteManyArgs>(args?: Prisma.SelectSubset<T, QuizQuestionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more QuizQuestions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuizQuestionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many QuizQuestions
   * const quizQuestion = await prisma.quizQuestion.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends QuizQuestionUpdateManyArgs>(args: Prisma.SelectSubset<T, QuizQuestionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more QuizQuestions and returns the data updated in the database.
   * @param {QuizQuestionUpdateManyAndReturnArgs} args - Arguments to update many QuizQuestions.
   * @example
   * // Update many QuizQuestions
   * const quizQuestion = await prisma.quizQuestion.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more QuizQuestions and only return the `id`
   * const quizQuestionWithIdOnly = await prisma.quizQuestion.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends QuizQuestionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, QuizQuestionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuizQuestionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one QuizQuestion.
   * @param {QuizQuestionUpsertArgs} args - Arguments to update or create a QuizQuestion.
   * @example
   * // Update or create a QuizQuestion
   * const quizQuestion = await prisma.quizQuestion.upsert({
   *   create: {
   *     // ... data to create a QuizQuestion
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the QuizQuestion we want to update
   *   }
   * })
   */
  upsert<T extends QuizQuestionUpsertArgs>(args: Prisma.SelectSubset<T, QuizQuestionUpsertArgs<ExtArgs>>): Prisma.Prisma__QuizQuestionClient<runtime.Types.Result.GetResult<Prisma.$QuizQuestionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of QuizQuestions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuizQuestionCountArgs} args - Arguments to filter QuizQuestions to count.
   * @example
   * // Count the number of QuizQuestions
   * const count = await prisma.quizQuestion.count({
   *   where: {
   *     // ... the filter for the QuizQuestions we want to count
   *   }
   * })
  **/
  count<T extends QuizQuestionCountArgs>(
    args?: Prisma.Subset<T, QuizQuestionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], QuizQuestionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a QuizQuestion.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuizQuestionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends QuizQuestionAggregateArgs>(args: Prisma.Subset<T, QuizQuestionAggregateArgs>): Prisma.PrismaPromise<GetQuizQuestionAggregateType<T>>

  /**
   * Group by QuizQuestion.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuizQuestionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends QuizQuestionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: QuizQuestionGroupByArgs['orderBy'] }
      : { orderBy?: QuizQuestionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, QuizQuestionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetQuizQuestionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the QuizQuestion model
 */
readonly fields: QuizQuestionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for QuizQuestion.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__QuizQuestionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  quiz<T extends Prisma.QuizDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.QuizDefaultArgs<ExtArgs>>): Prisma.Prisma__QuizClient<runtime.Types.Result.GetResult<Prisma.$QuizPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  question<T extends Prisma.QuestionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.QuestionDefaultArgs<ExtArgs>>): Prisma.Prisma__QuestionClient<runtime.Types.Result.GetResult<Prisma.$QuestionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the QuizQuestion model
 */
export interface QuizQuestionFieldRefs {
  readonly id: Prisma.FieldRef<"QuizQuestion", 'String'>
  readonly quizId: Prisma.FieldRef<"QuizQuestion", 'String'>
  readonly questionId: Prisma.FieldRef<"QuizQuestion", 'String'>
  readonly order: Prisma.FieldRef<"QuizQuestion", 'Int'>
  readonly createdAt: Prisma.FieldRef<"QuizQuestion", 'DateTime'>
}
    

// Custom InputTypes
/**
 * QuizQuestion findUnique
 */
export type QuizQuestionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizQuestion
   */
  select?: Prisma.QuizQuestionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizQuestion
   */
  omit?: Prisma.QuizQuestionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizQuestionInclude<ExtArgs> | null
  /**
   * Filter, which QuizQuestion to fetch.
   */
  where: Prisma.QuizQuestionWhereUniqueInput
}

/**
 * QuizQuestion findUniqueOrThrow
 */
export type QuizQuestionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizQuestion
   */
  select?: Prisma.QuizQuestionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizQuestion
   */
  omit?: Prisma.QuizQuestionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizQuestionInclude<ExtArgs> | null
  /**
   * Filter, which QuizQuestion to fetch.
   */
  where: Prisma.QuizQuestionWhereUniqueInput
}

/**
 * QuizQuestion findFirst
 */
export type QuizQuestionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizQuestion
   */
  select?: Prisma.QuizQuestionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizQuestion
   */
  omit?: Prisma.QuizQuestionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizQuestionInclude<ExtArgs> | null
  /**
   * Filter, which QuizQuestion to fetch.
   */
  where?: Prisma.QuizQuestionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuizQuestions to fetch.
   */
  orderBy?: Prisma.QuizQuestionOrderByWithRelationInput | Prisma.QuizQuestionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for QuizQuestions.
   */
  cursor?: Prisma.QuizQuestionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuizQuestions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuizQuestions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of QuizQuestions.
   */
  distinct?: Prisma.QuizQuestionScalarFieldEnum | Prisma.QuizQuestionScalarFieldEnum[]
}

/**
 * QuizQuestion findFirstOrThrow
 */
export type QuizQuestionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizQuestion
   */
  select?: Prisma.QuizQuestionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizQuestion
   */
  omit?: Prisma.QuizQuestionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizQuestionInclude<ExtArgs> | null
  /**
   * Filter, which QuizQuestion to fetch.
   */
  where?: Prisma.QuizQuestionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuizQuestions to fetch.
   */
  orderBy?: Prisma.QuizQuestionOrderByWithRelationInput | Prisma.QuizQuestionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for QuizQuestions.
   */
  cursor?: Prisma.QuizQuestionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuizQuestions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuizQuestions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of QuizQuestions.
   */
  distinct?: Prisma.QuizQuestionScalarFieldEnum | Prisma.QuizQuestionScalarFieldEnum[]
}

/**
 * QuizQuestion findMany
 */
export type QuizQuestionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizQuestion
   */
  select?: Prisma.QuizQuestionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizQuestion
   */
  omit?: Prisma.QuizQuestionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizQuestionInclude<ExtArgs> | null
  /**
   * Filter, which QuizQuestions to fetch.
   */
  where?: Prisma.QuizQuestionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuizQuestions to fetch.
   */
  orderBy?: Prisma.QuizQuestionOrderByWithRelationInput | Prisma.QuizQuestionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing QuizQuestions.
   */
  cursor?: Prisma.QuizQuestionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuizQuestions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuizQuestions.
   */
  skip?: number
  distinct?: Prisma.QuizQuestionScalarFieldEnum | Prisma.QuizQuestionScalarFieldEnum[]
}

/**
 * QuizQuestion create
 */
export type QuizQuestionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizQuestion
   */
  select?: Prisma.QuizQuestionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizQuestion
   */
  omit?: Prisma.QuizQuestionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizQuestionInclude<ExtArgs> | null
  /**
   * The data needed to create a QuizQuestion.
   */
  data: Prisma.XOR<Prisma.QuizQuestionCreateInput, Prisma.QuizQuestionUncheckedCreateInput>
}

/**
 * QuizQuestion createMany
 */
export type QuizQuestionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many QuizQuestions.
   */
  data: Prisma.QuizQuestionCreateManyInput | Prisma.QuizQuestionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * QuizQuestion createManyAndReturn
 */
export type QuizQuestionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizQuestion
   */
  select?: Prisma.QuizQuestionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the QuizQuestion
   */
  omit?: Prisma.QuizQuestionOmit<ExtArgs> | null
  /**
   * The data used to create many QuizQuestions.
   */
  data: Prisma.QuizQuestionCreateManyInput | Prisma.QuizQuestionCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizQuestionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * QuizQuestion update
 */
export type QuizQuestionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizQuestion
   */
  select?: Prisma.QuizQuestionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizQuestion
   */
  omit?: Prisma.QuizQuestionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizQuestionInclude<ExtArgs> | null
  /**
   * The data needed to update a QuizQuestion.
   */
  data: Prisma.XOR<Prisma.QuizQuestionUpdateInput, Prisma.QuizQuestionUncheckedUpdateInput>
  /**
   * Choose, which QuizQuestion to update.
   */
  where: Prisma.QuizQuestionWhereUniqueInput
}

/**
 * QuizQuestion updateMany
 */
export type QuizQuestionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update QuizQuestions.
   */
  data: Prisma.XOR<Prisma.QuizQuestionUpdateManyMutationInput, Prisma.QuizQuestionUncheckedUpdateManyInput>
  /**
   * Filter which QuizQuestions to update
   */
  where?: Prisma.QuizQuestionWhereInput
  /**
   * Limit how many QuizQuestions to update.
   */
  limit?: number
}

/**
 * QuizQuestion updateManyAndReturn
 */
export type QuizQuestionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizQuestion
   */
  select?: Prisma.QuizQuestionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the QuizQuestion
   */
  omit?: Prisma.QuizQuestionOmit<ExtArgs> | null
  /**
   * The data used to update QuizQuestions.
   */
  data: Prisma.XOR<Prisma.QuizQuestionUpdateManyMutationInput, Prisma.QuizQuestionUncheckedUpdateManyInput>
  /**
   * Filter which QuizQuestions to update
   */
  where?: Prisma.QuizQuestionWhereInput
  /**
   * Limit how many QuizQuestions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizQuestionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * QuizQuestion upsert
 */
export type QuizQuestionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizQuestion
   */
  select?: Prisma.QuizQuestionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizQuestion
   */
  omit?: Prisma.QuizQuestionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizQuestionInclude<ExtArgs> | null
  /**
   * The filter to search for the QuizQuestion to update in case it exists.
   */
  where: Prisma.QuizQuestionWhereUniqueInput
  /**
   * In case the QuizQuestion found by the `where` argument doesn't exist, create a new QuizQuestion with this data.
   */
  create: Prisma.XOR<Prisma.QuizQuestionCreateInput, Prisma.QuizQuestionUncheckedCreateInput>
  /**
   * In case the QuizQuestion was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.QuizQuestionUpdateInput, Prisma.QuizQuestionUncheckedUpdateInput>
}

/**
 * QuizQuestion delete
 */
export type QuizQuestionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizQuestion
   */
  select?: Prisma.QuizQuestionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizQuestion
   */
  omit?: Prisma.QuizQuestionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizQuestionInclude<ExtArgs> | null
  /**
   * Filter which QuizQuestion to delete.
   */
  where: Prisma.QuizQuestionWhereUniqueInput
}

/**
 * QuizQuestion deleteMany
 */
export type QuizQuestionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which QuizQuestions to delete
   */
  where?: Prisma.QuizQuestionWhereInput
  /**
   * Limit how many QuizQuestions to delete.
   */
  limit?: number
}

/**
 * QuizQuestion without action
 */
export type QuizQuestionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuizQuestion
   */
  select?: Prisma.QuizQuestionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuizQuestion
   */
  omit?: Prisma.QuizQuestionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuizQuestionInclude<ExtArgs> | null
}
